stages:
  - build

# build and push the container to harbor when a tag is created
build_container:
  stage: build
  image: docker:19.03.12-dind
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_IMG: harbor.lji.org/iedb-public/bcrmatch:$CI_COMMIT_TAG
  script:
    - docker logout $DOCKER_IMG
    - docker login -u $HARBOR_USER -p $HARBOR_PWD $DOCKER_IMG
    - docker build -t bcrmatch_img .
    - docker run --rm bcrmatch_img python3 -m unittest discover -s tests
    # - docker push $DOCKER_IMG 
  # rules:
  #   # run this only for tags
  #   - if: '$CI_COMMIT_TAG'
