stages:
  - test
  - deploy

# build and push the container to harbor when a tag is created
test_container:
  stage: test
  image: docker:19.03.12-dind
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_IMG: harbor.lji.org/iedb-public/bcrmatch:$CI_COMMIT_TAG
  script:
    - docker logout $DOCKER_IMG
    - docker login -u $HARBOR_USER -p $HARBOR_PWD $DOCKER_IMG
    - docker build -t bcrmatch_img .
    - docker run --rm bcrmatch_img bash -c "python3 pickle_score_distributions.py && python3 -m unittest discover -s tests"

push_container:
  stage: deploy
  image: docker:19.03.12-dind
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_IMG: harbor.lji.org/iedb-public/bcrmatch:$CI_COMMIT_TAG
  script:
    - docker logout $DOCKER_IMG
    - docker login -u $HARBOR_USER -p $HARBOR_PWD $DOCKER_IMG
    - docker build -t $DOCKER_IMG .
    - docker push $DOCKER_IMG
  rules:
    # run this only for tags
    - if: '$CI_COMMIT_TAG'
  when: manual
