stages:
  - build
  - test

variables:
  DOCKER_IMAGE_NAME: your-docker-image-name
  DOCKERFILE_PATH: ./Dockerfile
  TEST_COMMAND: python -m unittest discover

build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f $DOCKERFILE_PATH .
    - docker push $DOCKER_IMAGE_NAME

run-unit-tests:
  stage: test
  image: $DOCKER_IMAGE_NAME
  script:
    - $TEST_COMMAND